childBlocks: ''
field: 556a1513-344a-4436-9959-4d98ba8293c3
fieldLayouts:
  fddfad18-43ea-4b32-b749-a19dfdc8e0cb:
    tabs:
      -
        elements:
          -
            fieldUid: eb15e0c1-abf7-4dbe-b644-fc0a17c9b2e1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d6ed7b7-ed45-4e2e-afd9-929a99c7c69f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: imageBlock
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Image block'
sortOrder: 1
topLevel: true
