dateModified: 1608742756
email:
  fromEmail: noreply@hyperlane.to
  fromName: 'Muse Advisory'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.1.1
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    schemaVersion: 2.8.15
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Craft CMS Starter'
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
