enableVersioning: true
handle: privacyPolicy
name: 'Privacy policy'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  be77d207-3621-4807-b01c-db8bfa592a47:
    enabledByDefault: true
    hasUrls: true
    template: _pages/default/
    uriFormat: privacy-policy
type: single
